import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import NavBarComp from "../components/NavBarComp/NavBarComp";
import ComingSoonComp from "../components/ComingSoonComp/index";

import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({ subsets: ["latin"], weight: `[300, 400]` });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Cibara Shipping LLC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <Head>
          <link
            rel="icon"
            type="image/png"
            href="/favicon-48x48.png"
            sizes="48x48"
          />
          <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
          <link rel="shortcut icon" href="/favicon.ico" />
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/apple-touch-icon.png"
          />
          <meta name="apple-mobile-web-app-title" content="Cibara Shipping" />
          <link rel="manifest" href="/site.webmanifest" />
        </Head>
      </Head>
      <body className={openSans.className}>
        {/* <NavBarComp /> */}
        {children}
      </body>
    </html>
  );
}
